### ISSUE TITLE
CI/CD: publish precompiled polars-cli binaries to popular package managers.

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/polars-cli#13]
### Problem description

Polars CLI is currently only available if you compile from source. 
I wish I could easily install polars-cli through many of the common ways seen with other binaries

I'm not suggesting we support all of these to start. I think `brew` and github binaries would be a starting point.

## Through package managers
- [ ] `pip install polars-cli` (PyPI for Python packages)
- [ ] `brew install polars-cli` (Homebrew for macOS)
- [ ] `choco install polars-cli` (Chocolatey for Windows)
- [ ] `apt install polars-cli` (Advanced Package Tool for Debian-based Linux distributions)
- [ ] `yum install polars-cli` (Yellowdog Updater Modified for RPM-based Linux distributions)
- [ ] `pacman -S polars-cli` (Pacman for Arch Linux and its derivatives)

## Through an install script
- [ ] `curl -L https://install.pola.rs | sh`

## Via the "Releases" page. 
- [x] `wget https://github.com/repo/project/releases/download/{{version}}/{{file}}`

**Comment by stinodego** [comment]
These are all nice to have, but I'd rather that these options flow organically from the needs of our users.

We have a number of install options now:

* `pip install polars-cli` (pre-compiled, requires Python environment)
* Download binary from GitHub release assets
* Compile yourself by running `cargo install --locked polars-cli`

I think this is enough for now. If specific needs arise, we can address them as they pop up. Meanwhile, we can focus on improving the capabilities of the CLI and of Polars SQL.
