### ISSUE TITLE
polars-cli doesn't build: unkown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by ethanmsl** [pola-rs/polars-cli#16]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pola-rs/polars-cli/releases/latest) of the Polars CLI.

## Example
```shell
> cargo +nightly install --locked polars-cli
error[E0635]: unknown feature `proc_macro_span_shrink`
```

## Running context

`rustup 1.26.0 (5af9b9484 2023-04-05)`

`cargo 1.72.0 (103a7ff2e 2023-08-15)`

```sh
> rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/eskowronski-lutz/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin
1.62-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
x86_64-apple-darwin

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.72.0 (5680fa18f 2023-08-23)
```

## Alternate, older example
Using older install method, not locked to file:

```sh
> cargo install polars-cli
error[E0034]: multiple applicable items in scope
  --> /Users/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-arrow-0.31.1/src/array/get.rs:33:17
   |
33 |         if self.is_null_unchecked(item) {
   |                 ^^^^^^^^^^^^^^^^^ multiple `is_null_unchecked` found
   |
note: candidate #1 is defined in an impl of the trait `IsValid` for the type `A`
```

------------------

### Issue description

Uknown feature is preventing polar-cli from building.

-------------------------------

### Expected behavior

Note: 
This issues is also described [internally here](https://github.com/pola-rs/polars-cli/issues/6#issuecomment-1698234148), in a feature request.  Thought it deserved it's own bug issue, but, ofc, feel free to do with as is most useful.

### Installed version

0.3.0

**Comment by stinodego** [comment]
After releasing `0.4.0`, this seems to no longer be an issue.
