### ISSUE TITLE
polars-cli is using unstable rust

### ISSUE THREAD

**Issue by jgardona** [pola-rs/polars-cli#38]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pola-rs/polars-cli/releases/latest) of the Polars CLI.

### Reproducible example

```shell
cargo install --locked polars-cli
```

### Issue description

polars-cli is using unstable rust features. The build is failing as we can see in print below:

![image](https://github.com/pola-rs/polars-cli/assets/146892539/3f981283-044d-41e0-9ecc-7c3335009c49)

### Expected behavior

to compile.

### Installed version

0.5.0

**Comment by stinodego** [comment]
There was an issue with the `0.34.0` Polars release. 

Try either of the following:

```
cargo install --locked polars-cli
```
```
cargo +nightly install --locked polars-cli
```

**Comment by jgardona** [comment]
> There was an issue with the `0.34.0` Polars release.
> 
> Try either of the following:
> 
> ```
> cargo install polars-cli
> ```
> 
> ```
> cargo +nightly install --locked polars-cli
> ```
> 
> Next time I'll wait a bit with releasing the CLI until any issues with the Rust release have been ironed out. For now, I'll release `0.5.1` to fix this issue.

Removing --locked did it. Thank you.
