### ISSUE TITLE
Why are binaries not available?

### ISSUE THREAD

**Issue by zeritonius** [pola-rs/polars-cli#6]
### Description

>Until binaries are available, the only way to install the Polars CLI is by building it from source

If I make Windows binaries on my computer, can I submit them as a PR? Or is it a license problem with distributing the exe files created by Rust?

I don't want to sound disrespectful, but if you already built the binaries on your computer, why not publish them as a release? What am I missing, please?

Thank you.

**Comment by ritchie46** [comment]
We must setup CI to automatically build binaries for many OS architectures and CPU targets. We don't upload binaries built on our local machines. 

You are free helping setting up CI. As to why, because there are just so many hours in a day.

**Comment by zeritonius** [comment]
Thank you so much for your detailed explanation! Now it makes perfect sense to me. The missing part for me was the "automatically build".

I'm new to CI, but I'd like to help. Could you, please, give me some hints of where to start? Or, an existing repository that has CI, from which I can learn and adapt it to this one?

Thank you.

**Comment by ethack** [comment]
@zeritonius [this](https://github.com/BamPeers/rust-ci-github-actions-workflow) looks like a fairly recent decent example.

FWIW, I wasn't able to get it to build with `cargo +nightly install --locked polars-cli`. It failed with this error: 
```
error[E0635]: unknown feature `proc_macro_span_shrink`
```

I had to clone locally and use `cargo install --locked --path .` and that worked. I think the former was not picking up [the toolchain requirement](https://github.com/pola-rs/polars-cli/blob/main/rust-toolchain.toml).

**Comment by stinodego** [comment]
I am like 80% of the way there to setting up the CI, but I have been busy with the new `0.19` Polars release. Now that it's released, I can finish the CI here.

**Comment by stinodego** [comment]
Binaries are available as assets in the latest GitHub release!
